apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunger
  labels:
    app: hunger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunger
  template:
    metadata:
      labels:
        app: hunger
    spec:
      containers:
        - name: hunger
          image: username/hunger:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
